# Generated by Django 5.0.4 on 2024-04-21 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElearningPlatform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_participant',
            name='chatroom',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ElearningPlatform.chatroom'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ElearningPlatform.chat_participant'),
        ),
    ]
