# Generated by Django 5.0.4 on 2024-04-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElearningPlatform', '0002_chat_participant_chatroom_message_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_participant',
            name='chatroom',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='participants',
            field=models.ManyToManyField(to='ElearningPlatform.chat_participant'),
        ),
    ]
