# Generated by Django 5.0.4 on 2024-04-21 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElearningPlatform', '0003_remove_chat_participant_chatroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ElearningPlatform.course'),
        ),
    ]
